services:
  db:
    image: bitnami/postgresql:latest
    container_name: brevly-postgres
    restart: unless-stopped
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - brevly

  app:
    build: .
    depends_on:
      - db
    container_name: brevly-server
    restart: unless-stopped
    ports:
      - 3000:$PORT
    env_file: .env
    networks:
      - brevly

volumes:
  db:
networks:
  brevly:
    driver: bridge
  db:
    driver: bridge
